### ISSUE TITLE
How to get index of contentChild List?

### ISSUE THREAD

**Issue by ghost** [dangngocduc/comment_tree#10]
how to get index of content child list ?

contentChild: (context, value) {)

**Comment by gbbest15** [comment]
check my fork repo

if is what u like star the forked
```
 comment_tree:
    git:
      url: https://github.com/gbbest15/flutterCommentTree.git
      ref: master
```
